// Realistic sample seed data for Thai teachers

export const INITIAL_SEMESTERS = [
  {
    id: 'sem-2569-1',
    name: 'ภาคเรียนที่ 1/2569',
    academicYear: '2569',
    term: '1',
    startDate: '2026-05-18',
    endDate: '2026-10-09',
    isDefault: true,
  },
  {
    id: 'sem-2569-2',
    name: 'ภาคเรียนที่ 2/2569',
    academicYear: '2569',
    term: '2',
    startDate: '2026-11-02',
    endDate: '2027-03-12',
    isDefault: false,
  },
];

export const INITIAL_SUBJECTS = [
  {
    id: 'sub-1',
    code: 'ว31101',
    name: 'วิทยาการคำนวณ 1',
    defaultRoom: 'ห้องคอมพิวเตอร์ 2',
    gradeGroup: 'ม.4/1',
    colorId: 'indigo',
    periods: 2,
    description: 'การคิดเชิงคำนวณ และการเขียนโปรแกรมเบื้องต้น',
  },
  {
    id: 'sub-2',
    code: 'ว32202',
    name: 'ฟิสิกส์ 2 (กลศาสตร์)',
    defaultRoom: 'ห้องปฏิบัติการ 421',
    gradeGroup: 'ม.5/2',
    colorId: 'emerald',
    periods: 2,
    description: 'การเคลื่อนที่ แรง และกฎการเคลื่อนที่ของนิวตัน',
  },
  {
    id: 'sub-3',
    code: 'ค31101',
    name: 'คณิตศาสตร์พื้นฐาน',
    defaultRoom: 'ห้อง 314 อาคาร 3',
    gradeGroup: 'ม.4/3',
    colorId: 'amber',
    periods: 2,
    description: 'เซต ตรรกศาสตร์เบื้องต้น และจำนวนจริง',
  },
  {
    id: 'sub-4',
    code: 'ว30291',
    name: 'โครงงานวิทยาศาสตร์และเทคโนโลยี',
    defaultRoom: 'Lab วิจัย 1',
    gradeGroup: 'ม.6/1',
    colorId: 'rose',
    periods: 2,
    description: 'การศึกษาค้นคว้าอิสระและการจัดทำโครงงาน',
  },
  {
    id: 'sub-5',
    code: 'ว32103',
    name: 'การพัฒนาเว็บแอปพลิเคชัน',
    defaultRoom: 'ห้องคอมพิวเตอร์ 1',
    gradeGroup: 'ม.5/1',
    colorId: 'purple',
    periods: 2,
    description: 'พื้นฐาน HTML, CSS, JavaScript และ Web Development',
  },
  {
    id: 'sub-6',
    code: 'กจ401',
    name: 'กิจกรรมแนะแนวและพัฒนาผู้เรียน',
    defaultRoom: 'ห้อง 421 อาคาร 4',
    gradeGroup: 'ม.4/1',
    colorId: 'sky',
    periods: 1,
    description: 'กิจกรรมแนะแนวการศึกษาและทักษะชีวิต',
  },
];

export const INITIAL_TIMETABLE_SLOTS = [
  // วันจันทร์ (1)
  {
    id: 'slot-mon-1',
    semesterId: 'sem-2569-1',
    subjectId: 'sub-1',
    dayOfWeek: 1,
    startTime: '08:30',
    endTime: '10:10',
    periods: 2,
    roomOverride: 'ห้องคอมพิวเตอร์ 2',
  },
  {
    id: 'slot-mon-2',
    semesterId: 'sem-2569-1',
    subjectId: 'sub-2',
    dayOfWeek: 1,
    startTime: '10:20',
    endTime: '12:00',
    periods: 2,
    roomOverride: 'ห้องปฏิบัติการ 421',
  },
  {
    id: 'slot-mon-3',
    semesterId: 'sem-2569-1',
    subjectId: 'sub-3',
    dayOfWeek: 1,
    startTime: '13:00',
    endTime: '14:40',
    periods: 2,
    roomOverride: 'ห้อง 314 อาคาร 3',
  },

  // วันอังคาร (2)
  {
    id: 'slot-tue-1',
    semesterId: 'sem-2569-1',
    subjectId: 'sub-5',
    dayOfWeek: 2,
    startTime: '09:25',
    endTime: '11:05',
    periods: 2,
    roomOverride: 'ห้องคอมพิวเตอร์ 1',
  },
  {
    id: 'slot-tue-2',
    semesterId: 'sem-2569-1',
    subjectId: 'sub-4',
    dayOfWeek: 2,
    startTime: '13:00',
    endTime: '14:40',
    periods: 2,
    roomOverride: 'Lab วิจัย 1',
  },

  // วันพุธ (3)
  {
    id: 'slot-wed-1',
    semesterId: 'sem-2569-1',
    subjectId: 'sub-1',
    dayOfWeek: 3,
    startTime: '08:30',
    endTime: '10:10',
    periods: 2,
    roomOverride: 'ห้องคอมพิวเตอร์ 2',
  },
  {
    id: 'slot-wed-2',
    semesterId: 'sem-2569-1',
    subjectId: 'sub-3',
    dayOfWeek: 3,
    startTime: '10:20',
    endTime: '12:00',
    periods: 2,
    roomOverride: 'ห้อง 314 อาคาร 3',
  },
  {
    id: 'slot-wed-3',
    semesterId: 'sem-2569-1',
    subjectId: 'sub-6',
    dayOfWeek: 3,
    startTime: '14:50',
    endTime: '15:40',
    periods: 1,
    roomOverride: 'ห้อง 421 อาคาร 4',
  },

  // วันพฤหัสบดี (4)
  {
    id: 'slot-thu-1',
    semesterId: 'sem-2569-1',
    subjectId: 'sub-2',
    dayOfWeek: 4,
    startTime: '08:30',
    endTime: '10:10',
    periods: 2,
    roomOverride: 'ห้องปฏิบัติการ 421',
  },
  {
    id: 'slot-thu-2',
    semesterId: 'sem-2569-1',
    subjectId: 'sub-5',
    dayOfWeek: 4,
    startTime: '13:00',
    endTime: '14:40',
    periods: 2,
    roomOverride: 'ห้องคอมพิวเตอร์ 1',
  },

  // วันศุกร์ (5)
  {
    id: 'slot-fri-1',
    semesterId: 'sem-2569-1',
    subjectId: 'sub-4',
    dayOfWeek: 5,
    startTime: '09:25',
    endTime: '11:05',
    periods: 2,
    roomOverride: 'Lab วิจัย 1',
  },
  {
    id: 'slot-fri-2',
    semesterId: 'sem-2569-1',
    subjectId: 'sub-1',
    dayOfWeek: 5,
    startTime: '13:00',
    endTime: '14:40',
    periods: 2,
    roomOverride: 'ห้องคอมพิวเตอร์ 2',
  },
];

export const INITIAL_OVERRIDES = [
  {
    id: 'ovr-today',
    semesterId: 'sem-2569-1',
    date: '2026-09-17',
    slotId: 'slot-thu-1',
    subjectId: 'sub-2',
    status: 'normal',
    topic: 'การทดลองการเคลื่อนที่และกฎของนิวตัน',
    lessonPlan: 'แบ่งกลุ่ม 5 กลุ่ม ทำการทดลองวัดความเร่งและแรงดึง รวบรวมผลการทดลอง',
    prepChecklist: [
      { id: 'prep-1', text: 'เบิกชุดรางทดลองและเครื่องเคาะสัญญาณเวลา 8 ชุด', isDone: false },
      { id: 'prep-2', text: 'พิมพ์ใบงานการทดลอง 40 ชุด', isDone: true },
    ],
    notes: 'เตือนนักเรียนเรื่องการรักษาอุปกรณ์แล็บ',
  },
  {
    id: 'ovr-1',
    semesterId: 'sem-2569-1',
    date: '2026-09-18',
    slotId: 'slot-fri-1',
    subjectId: 'sub-4',
    status: 'activity',
    reason: 'กิจกรรมงานสัปดาห์วิทยาศาสตร์แห่งชาติและนิทรรศการโรงเรียน',
    topic: 'จัดซุ้มนิทรรศการโครงงาน',
    lessonPlan: 'นักเรียนดูแลซุ้มและตอบคำถามผู้เข้าชม',
    prepChecklist: [
      { id: 'prep-3', text: 'จัดเตรียมบอร์ดนิทรรศการและแผ่นพับสรุปโครงงาน', isDone: true },
    ],
    notes: 'ให้นักเรียนช่วยกันดูแลฐานการเรียนรู้',
  },
  {
    id: 'ovr-2',
    semesterId: 'sem-2569-1',
    date: '2026-09-18',
    slotId: 'slot-fri-2',
    subjectId: 'sub-1',
    status: 'activity',
    reason: 'กิจกรรมงานสัปดาห์วิทยาศาสตร์แห่งชาติและนิทรรศการโรงเรียน',
    topic: 'งดการเรียนในห้องคอมฯ ร่วมกิจกรรมหน้าลานอเนกประสงค์',
    notes: '',
  },
  {
    id: 'ovr-3',
    semesterId: 'sem-2569-1',
    date: '2026-09-21',
    slotId: 'slot-mon-1',
    subjectId: 'sub-1',
    status: 'cancelled',
    reason: 'ติดราชการอบรมเชิงปฏิบัติการ การนำ AI มาใช้ในการจัดการเรียนการสอน',
    topic: 'งดสอน 1 คาบ',
    notes: 'ฝากงานแบบฝึกหัดบทที่ 4 ให้นักเรียนทำใน Google Classroom',
  },
  {
    id: 'ovr-next-week',
    semesterId: 'sem-2569-1',
    date: '2026-09-22',
    slotId: 'slot-tue-2',
    subjectId: 'sub-4',
    status: 'normal',
    topic: 'วิเคราะห์ข้อมูลสถิติและการนำเสนอผลโครงงาน',
    lessonPlan: 'บรรยายการเลือกใช้สถิติ และตรวจร่างรายงานบทที่ 4 รายกลุ่ม',
    prepChecklist: [
      { id: 'prep-4', text: 'เตรียมไฟล์ตัวอย่างการใช้โปรแกรมคำนวณสถิติ', isDone: false },
      { id: 'prep-5', text: 'พิมพ์แบบประเมินความก้าวหน้าโครงงาน 10 ชุด', isDone: false },
    ],
    notes: 'นัดตัวแทนกลุ่มนำไฟล์ข้อมูลดิบมาส่ง',
  },
  {
    id: 'ovr-4',
    semesterId: 'sem-2569-1',
    date: '2026-09-23',
    slotId: 'sub-1',
    subjectId: 'sub-1',
    isCustomSession: true, // One-off makeup session
    startTime: '15:45',
    endTime: '17:00',
    room: 'ห้องคอมพิวเตอร์ 2',
    status: 'makeup',
    reason: 'สอนชดเชยคาบของวันจันทร์ที่ 21 ก.ย.',
    topic: 'เขียนโปรแกรมอัลกอริทึม เงื่อนไขและการวนซ้ำ',
    lessonPlan: 'ฝึกเขียน Flowchart และโค้ดภาษา Python ด้วย Replit',
    prepChecklist: [
      { id: 'prep-6', text: 'ตรวจสอบบัญชี Replit ในห้องคอมพิวเตอร์ 2', isDone: true },
    ],
    notes: 'นัดหมายนักเรียน ม.4/1 เรียบร้อยแล้ว',
  },
];

export const INITIAL_MULTI_DAY_EVENTS = [
  {
    id: 'mde-1',
    semesterId: 'sem-2569-1',
    title: 'งานสัปดาห์วิทยาศาสตร์และนิทรรศการวิชาการ',
    startDate: '2026-09-16',
    endDate: '2026-09-18',
    type: 'activity',
    cancelClasses: true,
    notes: 'จัดซุ้มนิทรรศการและแข่งขันทักษะวิชาการตลอด 3 วัน งดการเรียนการสอนปกติ',
    colorId: 'amber',
  },
];

export const INITIAL_SHORT_NOTES = [
  {
    id: 'note-1',
    subjectId: 'sub-2', // ฟิสิกส์ 2 ม.5/2
    title: 'ส่งสมุดแบบฝึกหัดบทที่ 2 (กฎของนิวตัน)',
    dueDate: '2026-09-17',
    duePeriod: 'คาบที่ 2 (09:20 - 10:10 น.)',
    description: 'ส่งที่โต๊ะหัวหน้าห้องท้ายคาบ เพื่อรวบรวมส่งห้องพักครู 421 (10 คะแนน)',
    isCompleted: false,
    createdAt: '2026-09-10T08:30:00.000Z',
    completedAt: null,
  },
  {
    id: 'note-2',
    subjectId: 'sub-1', // วิทยาการคำนวณ 1 ม.4/1
    title: 'ส่งไฟล์ผังงาน Flowchart อัลกอริทึม',
    dueDate: '2026-09-18',
    duePeriod: 'ก่อน 16:30 น.',
    description: 'อัปโหลดไฟล์ PDF ขึ้นระบบ Google Classroom หรือส่ง flash drive ที่ห้องคอมพิวเตอร์ 2',
    isCompleted: false,
    createdAt: '2026-09-12T10:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'note-3',
    subjectId: 'sub-4', // โครงงานวิทยาศาสตร์ ม.6/1
    title: 'ส่งรายงานความก้าวหน้าบทที่ 1-3',
    dueDate: '2026-09-24',
    duePeriod: 'คาบที่ 5-6',
    description: 'พิมพ์เข้าเล่มฉบับร่าง 1 ชุด พร้อมไฟล์นำเสนอ Powerpoint สำหรับซักถามกลุ่ม',
    isCompleted: false,
    createdAt: '2026-09-15T13:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'note-4',
    subjectId: 'sub-3', // คณิตศาสตร์พื้นฐาน ม.4/3
    title: 'ส่งใบงานเรื่องเซตและสับเซต',
    dueDate: '2026-09-15',
    duePeriod: 'คาบที่ 4',
    description: 'ตรวจและลงคะแนนในสมุดบันทึกคะแนนเรียบร้อยแล้ว',
    isCompleted: true,
    createdAt: '2026-09-08T09:00:00.000Z',
    completedAt: '2026-09-15T12:00:00.000Z',
  },
];

